version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  dbt:
    container_name: dbt
    build: .
    volumes:
      - ./:/usr/src/dbt
    entrypoint: ["tail", "-f", "/dev/null"]  # Keeps container running for interactive use

  dagster:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    image: dagster-user-code:latest
    container_name: dagster
    depends_on:
      - postgres
    working_dir: /opt/dagster/app/
    ports:
      - "3000:3000"
    command: ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "3000"]

  dagit:
    build:
      context: .
      dockerfile: Dockerfile.dagit
    image: dagster-dagit:latest
    container_name: dagit
    depends_on:
      - dagster
    working_dir: /opt/dagster/app
    ports:
      - "8080:8080"
    environment:
      DAGSTER_GRPC_SERVER_HOST: dagster
      DAGSTER_GRPC_SERVER_PORT: 3000
    command: ["dagit", "-h", "0.0.0.0", "-p", "8080", "-w", "workspace.yaml"]

volumes:
  postgres_data: