FROM python:3.11-slim

WORKDIR /opt/dagster/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY __init__.py ./
COPY repository.py ./
COPY workspace.yaml ./

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "3000"] 