FROM python:3.11-slim

WORKDIR /opt/dagster/app

COPY dagster_requirements.txt ./
COPY dbtpostgres ./dbtpostgres

COPY repository.py ./
COPY workspace.yaml ./
COPY __init__.py ./

RUN pip install --no-cache-dir -r dagster_requirements.txt



CMD ["dagit", "-h", "0.0.0.0", "-p", "8080", "-w", "workspace.yaml"] 