FROM python:3.11-slim

WORKDIR /opt/dagster/app

COPY requirements.txt ./

COPY repository.py ./
COPY workspace.yaml ./
COPY __init__.py ./

RUN pip install --no-cache-dir -r requirements.txt


CMD ["dagit", "-h", "0.0.0.0", "-p", "8080", "-w", "workspace.yaml"] 